# Generated by Django 4.2.1 on 2023-06-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0002_link_db_code_alter_link_db_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link_db',
            name='code',
        ),
    ]
