# Generated by Django 4.2.1 on 2023-06-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0003_remove_link_db_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='link_db',
        ),
    ]
