# Generated by Django 4.2.1 on 2023-06-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_db',
            name='link_id',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
